// <auto-generated />
using System;
using CleaningRobotService.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleaningRobotService.Web.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20221007154641_AddExecutions")]
    partial class AddExecutions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleaningRobotService.Web.Models.Execution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Commands")
                        .HasColumnType("integer")
                        .HasColumnName("commands");

                    b.Property<float>("Duration")
                        .HasColumnType("real")
                        .HasColumnName("duration");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeStamp");

                    b.HasKey("Id")
                        .HasName("pK_executions");

                    b.ToTable("executions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
