// <auto-generated />
using System;
using CleaningRobotService.DataPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleaningRobotService.DataPersistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20230129222500_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("StartPointX")
                        .HasColumnType("integer")
                        .HasColumnName("start_point_x");

                    b.Property<int>("StartPointY")
                        .HasColumnType("integer")
                        .HasColumnName("start_point_y");

                    b.HasKey("Id")
                        .HasName("pk_commands");

                    b.ToTable("commands", (string)null);
                });

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.DirectionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<long>("Steps")
                        .HasColumnType("bigint")
                        .HasColumnName("steps");

                    b.HasKey("Id")
                        .HasName("pk_direction_steps");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_direction_steps_command_id");

                    b.ToTable("direction_steps", (string)null);
                });

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<int>("Commands")
                        .HasColumnType("integer")
                        .HasColumnName("commands");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int?>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.HasKey("Id")
                        .HasName("pk_executions");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_executions_command_id");

                    b.ToTable("executions", (string)null);
                });

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.DirectionStep", b =>
                {
                    b.HasOne("CleaningRobotService.DataPersistence.Models.Command", null)
                        .WithMany("DirectionSteps")
                        .HasForeignKey("CommandId")
                        .HasConstraintName("fk_direction_steps_commands_command_id");
                });

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.Execution", b =>
                {
                    b.HasOne("CleaningRobotService.DataPersistence.Models.Command", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_executions_commands_command_id");

                    b.Navigation("Command");
                });

            modelBuilder.Entity("CleaningRobotService.DataPersistence.Models.Command", b =>
                {
                    b.Navigation("DirectionSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
